version: 2.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true

environment:
  LOGGER: '/l:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"'

build_script:
  - cmd: dotnet --version
  - cmd: dotnet build %LOGGER% -v m -c Release

test_script:
  - cmd: dotnet test -v m -c Release --test-adapter-path:. --logger:Appveyor


artifacts:
  - path: '**\*.nupkg'
    name: nupkg
  - path: '**\*.snupkg'
    name: snupkg


cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%USERPROFILE%\.nuget\packages'